server: "http://localhost:8080"
interval: 5
publish: # left empty to publish all network interfaces
subscribe: # use 'all' or left empty to subscribe all hosts
# publish: ["wlp132s0", "enp131s0", "cscotun0"] # publish selected interfaces
# subscribe:
#   - "host1:wlp132s0+eth" # subscribe to host1's 2 interface
mapping:
  - "host2:wlp132s0=host2-wifi"
password: "123"
excluded_interface_patterns: ["lo", "docker0", "utun.*"]
subscribe_config: True
